spring.application.name=yt-spotify-sync
spring.profiles.active=local

youtube.max-results=50
youtube.part=snippet
youtube.api-url=https://www.googleapis.com/youtube/v3/playlistItems
spotify.client.id=3fffdf39fb4644e4bea9f4cf4bb85e76
spotify.redirect.uri=http://127.0.0.1:8080/spotify/callback